グラフの下にテーブルを表示する
covid19-oita/covid19 pull request #203
Opened 2020-04-23 06:26 UTC by nojiri1098

## 👏 解決する issue / Resolved Issues
- close #199 

## 📸 スクリーンショット / Screenshots

デフォルト
![image](https://user-images.githubusercontent.com/24912801/80066280-9aebc800-8576-11ea-999b-c07638d70ad1.png)

開いたとき
![image](https://user-images.githubusercontent.com/24912801/80066324-accd6b00-8576-11ea-9e92-fc41f9658afc.png)

2020-04-23 06:51 UTC, nojiri1098 commented
TOSでも問題なし

2020-04-23 09:20 UTC, shmokmt commented on assets/variables.scss
> +// Vuetify
おお、vuetify

2020-04-23 09:20 UTC, shmokmt commented
ゆっくりレビューしたいので、明日まで待ってください 🙏

2020-04-23 09:48 UTC, nojiri1098 commented
ここで動作確認できます
https://deploy-preview-203--review-covid19-oita.netlify.app/

2020-04-23 10:17 UTC, shmokmt requested changes

2020-04-23 10:17 UTC, shmokmt commented on components/DataView.vue
> +                $t('テーブルを表示')
これの国際化ができてないみたい

2020-04-23 10:18 UTC, nojiri1098 commented on components/DataView.vue
> +                $t('テーブルを表示')
i18n忘れてた，ありがとう

2020-04-24 01:20 UTC, shmokmt commented on components/DataView.vue
> +                $t('テーブルを表示')
あとは、タイ語かな？

2020-04-24 01:24 UTC, nojiri1098 commented on components/DataView.vue
> +                $t('テーブルを表示')
ナットにお願いしようと思ったんだけど，毎回お願いするのが申し訳ないから，ある程度溜まってからお願いしようと思ってる
Google翻訳でもいいけど，どう思う？

2020-04-25 03:31 UTC, nojiri1098 commented on components/DataView.vue
> +                $t('テーブルを表示')
@shmokmt とりあえずタイ語を英語で追加してます

2020-04-25 06:12 UTC, shmokmt commented on components/DataView.vue
> +                $t('テーブルを表示')
@nojiri1098 🙆‍♀️

2020-04-25 06:13 UTC, shmokmt approved these changes

2020-04-25 06:37 UTC, merged