年代が非公開の患者の表示対応
covid19-oita/covid19 pull request #207
Opened 2020-04-24 05:13 UTC by nojiri1098

## 👏 解決する issue / Resolved Issues
- close #205 
- close #206 

## 📸 スクリーンショット / Screenshots

「非公開」と表示
![image](https://user-images.githubusercontent.com/24912801/80176842-d6e56280-8634-11ea-9ca6-cd01a447b53d.png)

注釈を追加
![image](https://user-images.githubusercontent.com/24912801/80177068-81f61c00-8635-11ea-836c-312078ae5493.png)

2020-04-24 14:17 UTC, nojiri1098 commented
「非公表」の表示対応は https://github.com/covid19-oita/data/pull/64 でやるので，こちらでは削除する

2020-04-25 03:25 UTC, shmokmt approved these changes

2020-04-25 06:48 UTC, nojiri1098 commented
covid19-oita/data#64 が終わり次第マージ

2020-04-25 09:30 UTC, PNNutkung requested changes

2020-04-25 09:30 UTC, PNNutkung commented on assets/locales/th.json
> +  "非公開": "Undisclosed",
`"非公開": "ไม่เปิดเผย",`

2020-04-25 09:30 UTC, PNNutkung commented on assets/locales/th.json
> +  "年代が公開されていない患者は含まれていません。": "This is not all patients. Patients that ages are undisclosed is not included.",
"年代が公開されていない患者は含まれていません。": "นี่ไม่ใช่จำนวนผู้ป่วยทั้งหมด ผู้ป่วยที่ไม่เปิดเผยอายุจะไม่ถูกนับ",

2020-04-25 09:43 UTC, nojiri1098 commented on assets/locales/th.json
> +  "年代が公開されていない患者は含まれていません。": "This is not all patients. Patients that ages are undisclosed is not included.",
awesome!

2020-04-25 09:57 UTC, merged