data.jsonをcommit & pushするタスクを追加した
covid19-oita/covid19 pull request #90
Opened 2020-03-28 05:29 UTC by varusan

## 👏 解決する issue / Resolved Issues
- close #89

## ⛏ 変更内容 / Details of Changes
- data.jsonを生成した後にgit commit & pushするように修正した

2020-03-28 05:39 UTC, nojiri1098 requested changes

2020-03-28 05:39 UTC, nojiri1098 commented on .github/workflows/build.yml
> +          branch: staging
@varusan 
今の運用では staiging を使用していないのですが，これが実行されると staging を挟むことになるでしょうか

2020-03-28 05:39 UTC, nojiri1098 commented on .github/workflows/deploy.yml
> +          git commit -m '[ci skip] Update Data (commited by GitHub Actions)" -a'
@varusan 
`"` が足りない気がしますが，こういう書き方なんでしょうか？(他の箇所も)

2020-03-28 08:12 UTC, varusan commented on .github/workflows/build.yml
> +          branch: staging
staging使用されていないのでしたらこのタスクは不要ですね。修正します。

2020-03-28 08:16 UTC, varusan commented on .github/workflows/deploy.yml
> +          git commit -m '[ci skip] Update Data (commited by GitHub Actions)" -a'
複数行のコマンドの際はこのような記法となります

FIY: 
https://help.github.com/ja/actions/reference/workflow-syntax-for-github-actions#

2020-03-28 08:20 UTC, nojiri1098 commented on .github/workflows/deploy.yml
> +          git commit -m '[ci skip] Update Data (commited by GitHub Actions)" -a'
そうなんですね，わかりました

2020-03-28 08:20 UTC, varusan commented on .github/workflows/deploy.yml
> +          git commit -m '[ci skip] Update Data (commited by GitHub Actions)" -a'
typoでした


`git commit -am "[ci skip] Update Data (commited by GitHub Actions)"`

2020-03-29 04:25 UTC, varusan commented
修正しました

2020-03-29 04:34 UTC, nojiri1098 approved these changes
ありがとうございます！

2020-03-29 04:35 UTC, merged